<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Core/ChartSettingsViewModel.cs" />
    <Compile Remove="Core/PythonBridge.cs" />
    <Page Remove="UI/**/*.xaml" />
  </ItemGroup>

</Project>
